/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var w=Object.defineProperty;var y=Object.getOwnPropertyDescriptor;var M=Object.getOwnPropertyNames;var $=Object.prototype.hasOwnProperty;var O=(o,t)=>{for(var e in t)w(o,e,{get:t[e],enumerable:!0})},P=(o,t,e,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of M(t))!$.call(o,i)&&i!==e&&w(o,i,{get:()=>t[i],enumerable:!(n=y(t,i))||n.enumerable});return o};var A=o=>P(w({},"__esModule",{value:!0}),o);var k={};O(k,{default:()=>p});module.exports=A(k);var g=require("obsidian");var T=require("obsidian"),C={tocTitle:"Table of Contents"},u=class extends T.PluginSettingTab{constructor(t,e){super(t,e),this.plugin=e}display(){let{containerEl:t}=this;t.empty(),new T.Setting(t).setName("Title").setDesc("The heading displayed above the table of contents. Leave blank for no title.").addText(e=>e.setPlaceholder("Table Of Contents").setValue(this.plugin.settings.tocTitle).onChange(async n=>{this.plugin.settings.tocTitle=n,await this.plugin.saveSettings()}))}};var p=class extends g.Plugin{async onload(){await this.loadSettings(),this.addCommand({id:"generate-toc",name:"Generate table of contents",editorCallback:(t,e)=>{this.generateToc(t)}}),this.addCommand({id:"update-toc",name:"Update existing table of contents",editorCallback:(t,e)=>{this.updateToc(t)}}),this.addSettingTab(new u(this.app,this))}onunload(){}async loadSettings(){this.settings=Object.assign({},C,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}generateToc(t){let e=t.getCursor(),n=e,i=e;this.generateTocAtPosition(t,n,i)}updateToc(t){let n=t.getValue().split(`
`),i=/^\s*- \[.*\]\(#.*\)$/,s=-1,b=-1;for(let c=0;c<n.length;c++){let m=n[c];if(i.test(m))s===-1&&(s=c),b=c;else if(s!==-1)break}if(s===-1){new g.Notice("No existing table of contents found.");return}let l=s,a=b;s>0&&/^#{1,6}\s+/.test(n[s-1])&&(l=s-1),a+1<n.length&&/^---$/.test(n[a+1])&&(a=a+1);let r={line:l,ch:0},d={line:a,ch:n[a].length};this.generateTocAtPosition(t,r,d,l,a)}generateTocAtPosition(t,e,n,i,s){let l=t.getValue().split(`
`),a=/^(#{1,6})\s+(.*)/,r=[];for(let h=0;h<l.length;h++){if(i!==void 0&&s!==void 0&&h>=i&&h<=s)continue;let f=l[h].match(a);if(f&&f[1]&&f[2]){let E=f[1].length,S=f[2],x=S.toLowerCase().replace(/[^\w\s]/g,"").replace(/\s+/g,"-"),v="  ".repeat(E-1);r.push(`${v}- [${S}](#${x})`)}}if(r.length===0){new g.Notice("No headings found.");return}let d=e.line===n.line&&e.ch===n.ch,c=this.settings.tocTitle.trim(),m=c?`# ${c}
${r.join(`
`)}
---${d?`
`:""}`:`${r.join(`
`)}
---${d?`
`:""}`;t.replaceRange(m,e,n),new g.Notice(d?"Table of contents generated!":"Table of contents updated!")}};
