/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var g=Object.defineProperty;var b=Object.getOwnPropertyDescriptor;var w=Object.getOwnPropertyNames;var u=Object.prototype.hasOwnProperty;var C=(n,t)=>{for(var a in t)g(n,a,{get:t[a],enumerable:!0})},M=(n,t,a,i)=>{if(t&&typeof t=="object"||typeof t=="function")for(let e of w(t))!u.call(n,e)&&e!==a&&g(n,e,{get:()=>t[e],enumerable:!(i=b(t,e))||i.enumerable});return n};var E=n=>M(g({},"__esModule",{value:!0}),n);var O={};C(O,{default:()=>c});module.exports=E(O);var s=require("obsidian");var r={mySetting:"default"};var c=class extends s.Plugin{async onload(){await this.loadSettings(),this.addCommand({id:"generate-toc",name:"Generate table of contents",editorCallback:(t,a)=>{this.generateToc(t)}})}onunload(){}async loadSettings(){this.settings=Object.assign({},r,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}generateToc(t){let i=t.getValue().split(`
`),e=[],d=/^(#{1,6})\s+(.*)/;for(let S of i){let o=S.match(d);if(o&&o[1]&&o[2]){let T=o[1].length,l=o[2],h=l.toLowerCase().replace(/[^\w\s]/g,"").replace(/\s+/g,"-"),m="  ".repeat(T-1);e.push(`${m}- [${l}](#${h})`)}}if(e.length===0){new s.Notice("No headings found.");return}let f=`## Table of Contents
${e.join(`
`)}
---
`,p=t.getCursor();t.replaceRange(f,p),new s.Notice("Table of contents generated!")}};
