/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var m=Object.defineProperty;var C=Object.getOwnPropertyDescriptor;var E=Object.getOwnPropertyNames;var x=Object.prototype.hasOwnProperty;var v=(a,t)=>{for(var e in t)m(a,e,{get:t[e],enumerable:!0})},y=(a,t,e,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of E(t))!x.call(a,s)&&s!==e&&m(a,s,{get:()=>t[s],enumerable:!(n=C(t,s))||n.enumerable});return a};var M=a=>y(m({},"__esModule",{value:!0}),a);var O={};v(O,{default:()=>T});module.exports=M(O);var r=require("obsidian");var p=require("obsidian"),w={tocTitle:"Table of Contents"},f=class extends p.PluginSettingTab{constructor(t,e){super(t,e),this.plugin=e}display(){let{containerEl:t}=this;t.empty(),new p.Setting(t).setName("Title").setDesc("The heading displayed above the table of contents. Leave blank for no title.").addText(e=>e.setPlaceholder("Table Of Contents").setValue(this.plugin.settings.tocTitle).onChange(async n=>{this.plugin.settings.tocTitle=n,await this.plugin.saveSettings()}))}};var T=class extends r.Plugin{async onload(){await this.loadSettings(),this.addCommand({id:"generate-toc",name:"Generate table of contents",editorCallback:(t,e)=>{this.generateToc(t)}}),this.addCommand({id:"update-toc",name:"Update existing table of contents",editorCallback:(t,e)=>{this.updateToc(t)}}),this.addSettingTab(new f(this.app,this))}onunload(){}async loadSettings(){this.settings=Object.assign({},w,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}generateToc(t){let e=t.getCursor();this.generateTocAtPosition(t,e)}updateToc(t){let n=t.getValue().split(`
`),s=/^\s*- \[.*\]\(#.*\)$/,o=-1,l=-1;for(let g=0;g<n.length;g++){let S=n[g];if(s.test(S))o===-1&&(o=g),l=g;else if(o!==-1)break}if(o===-1){new r.Notice("No existing table of contents found.");return}let d=o,i=l,c=/^#{1,6}\s+/;o>0&&c.test(n[o-1])&&(d=o-1);let u=/^---$/;i+1<n.length&&u.test(n[i+1])&&(i=i+1);let h={line:d,ch:0},b=i+1<n.length?{line:i+1,ch:0}:{line:i,ch:n[i].length};t.replaceRange("",h,b),this.generateTocAtPosition(t,h)}generateTocAtPosition(t,e){let s=t.getValue().split(`
`),o=/^(#{1,6})\s+(.*)/,l=[];for(let i=0;i<s.length;i++){let c=s[i].match(o);if(c&&c[1]&&c[2]){let u=c[1].length,h=c[2],b=h.toLowerCase().replace(/[^\w\s]/g,"").replace(/\s+/g,"-"),g="  ".repeat(u-1);l.push(`${g}- [${h}](#${b})`)}}if(l.length===0){new r.Notice("No headings found.");return}let d=this.settings.tocTitle.trim();d?t.replaceRange(`# ${d}
${l.join(`
`)}
---
`,e):t.replaceRange(`${l.join(`
`)}
---
`,e),new r.Notice("Table of contents generated!")}};
